CREATE TABLE IF NOT EXISTS "products" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "source_site" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "image_url" TEXT NOT NULL DEFAULT '',
    "cash_price" NUMERIC(12,2) NOT NULL,
    "installment_price" NUMERIC(12,2) NOT NULL,
    "installments_count" INTEGER NOT NULL DEFAULT 1,
    "product_url" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS "products_created_at_idx"
    ON "products" ("created_at" DESC);
